### ISSUE TITLE
Still uses "hunter2" as admin password

### ISSUE THREAD

**Issue by mitchellgordon95** [ehzhang/HELPq#1]
Even after changing the admin password in config.json, the application still requires "hunter2" as the password for the admin account.

**Comment by ehzhang** [comment]
The account password remains because the account still exists - from this line: https://github.com/ehzhang/HELPq/blob/master/server/startup.js#L34

You will have to remove the account from the database before you start up the server again with the new config.json value.

You can also change it manually by invoking the Accounts.changePassword function from the client in the javascript console:
http://docs.meteor.com/#/full/accounts_changepassword

Though it may actually be useful to reset the password each time, but I chose not to do that originally in order to preserve the account (instead of destroying/creating the account each time).

Let me know if that works for you!

**Comment by mitchellgordon95** [comment]
That did the trick! Thanks Edwin!
